<template>
  <RiAddCircleFill/>
  <RiAddCircleLine/>
  <RiArrowDownDoubleLine/>
  <RiArrowLeftRightLine/>
  <RiArrowLeftSLine/>
  <RiArrowRightSLine/>
  <RiArrowUpDoubleLine/>
  <RiBarChartHorizontalLine/>
  <RiBubbleChartLine/>
  <RiCalendar2Line/>
  <RiCalendarCheckLine/>
  <RiCalendarLine/>
  <RiCalendarTodoLine/>
  <RiCheckLine/>
  <RiCloseCircleFill/>
  <RiCloseCircleLine/>
  <RiCloseLine/>
  <RiCloudLine/>
  <RiCloudOffFill/>
  <RiCloudOffLine/>
  <RiContractUpDownLine/>
  <RiDashboardLine/>
  <RiDeleteBin5Line/>
  <RiDonutChartLine/>
  <RiDownload2Line/>
  <RiDownloadCloud2Line/>
  <RiDraggable/>
  <RiEarthLine/>
  <RiErrorWarningLine/>
  <RiExpandUpDownLine/>
  <RiEyeCloseLine/>
  <RiEyeLine/>
  <RiFileCopyLine/>
  <RiFileFill/>
  <RiFocus2Fill/>
  <RiFunctions/>
  <RiGitMergeLine/>
  <RiGlobalOffFill/>
  <RiGoogleFill/>
  <RiHandCoinLine/>
  <RiImageLine/>
  <RiIndeterminateCircleFill/>
  <RiInformationLine/>
  <RiKey2Line/>
  <RiLandscapeLine/>
  <RiLoader2Fill/>
  <RiLockLine/>
  <RiLockUnlockLine/>
  <RiLoginCircleLine/>
  <RiLoopRightLine/>
  <RiMagicFill/>
  <RiMagicLine/>
  <RiMoonFill/>
  <RiNumber9/>
  <RiPercentFill/>
  <RiRefreshFill/>
  <RiRefreshLine/>
  <RiResetLeftLine/>
  <RiSettings4Line/>
  <RiShieldFlashLine/>
  <RiShieldUserLine/>
  <RiShoppingBagLine/>
  <RiShoppingBasket2Line/>
  <RiSignalWifiErrorLine/>
  <RiSkipDownLine/>
  <RiSkipUpLine/>
  <RiSnowflakeLine/>
  <RiSunFill/>
  <RiTableLine/>
  <RiToolsLine/>
  <RiUploadCloud2Line/>
  <RiUserAddLine/>
  <RiUserSettingsLine/>
</template>

<script setup lang="ts">
import {
  RiAddCircleFill,
  RiAddCircleLine,
  RiArrowDownDoubleLine,
  RiArrowLeftRightLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArrowUpDoubleLine,
  RiBarChartHorizontalLine,
  RiBubbleChartLine,
  RiCalendar2Line,
  RiCalendarCheckLine,
  RiCalendarLine,
  RiCalendarTodoLine,
  RiCheckLine,
  RiCloseCircleFill,
  RiCloseCircleLine,
  RiCloseLine,
  RiCloudLine,
  RiCloudOffFill,
  RiCloudOffLine,
  RiContractUpDownLine,
  RiDashboardLine,
  RiDeleteBin5Line,
  RiDonutChartLine,
  RiDownload2Line,
  RiDownloadCloud2Line,
  RiDraggable,
  RiEarthLine,
  RiErrorWarningLine,
  RiExpandUpDownLine,
  RiEyeCloseLine,
  RiEyeLine,
  RiFileCopyLine,
  RiFileFill,
  RiFocus2Fill,
  RiFunctions,
  RiGitMergeLine,
  RiGlobalOffFill,
  RiGoogleFill,
  RiHandCoinLine,
  RiImageLine,
  RiIndeterminateCircleFill,
  RiInformationLine,
  RiKey2Line,
  RiLandscapeLine,
  RiLoader2Fill,
  RiLockLine,
  RiLockUnlockLine,
  RiLoginCircleLine,
  RiLoopRightLine,
  RiMagicFill,
  RiMagicLine,
  RiMoonFill,
  RiNumber9,
  RiPercentFill,
  RiRefreshFill,
  RiRefreshLine,
  RiResetLeftLine,
  RiSettings4Line,
  RiShieldFlashLine,
  RiShieldUserLine,
  RiShoppingBagLine,
  RiShoppingBasket2Line,
  RiSignalWifiErrorLine,
  RiSkipDownLine,
  RiSkipUpLine,
  RiSnowflakeLine,
  RiSunFill,
  RiTableLine,
  RiToolsLine,
  RiUploadCloud2Line,
  RiUserAddLine,
  RiUserSettingsLine
} from '@remixicon/vue';
</script>
